"use client";

import { emoteAssets, npcAssets } from "@/lib/asset-catalog";
import type { AmbientSpriteDefinition } from "./town-map-overlay-types";

export const OVERWORLD_AMBIENT_SPRITES: AmbientSpriteDefinition[] = [
	{
		id: "npc-1-north",
		src: npcAssets[5].src,
		x: 462,
		y: 334,
		columns: 4,
		rows: 4,
		renderWidth: 36,
		renderHeight: 36,
		row: 0,
		idleFrame: 0,
		idleColumn: 1,
		walkFrames: [0, 1, 0, 3],
		animateAxis: "column",
		animationFrames: 4,
		shadow: true,
		emote: {
			src: emoteAssets[8].src,
			x: 9,
			y: -20,
			columns: 1,
			rows: 5,
			renderWidth: 18,
			renderHeight: 18,
			animateAxis: "row",
			animationFrames: 5,
		},
	},
	{
		id: "npc-2-north",
		src: npcAssets[6].src,
		x: 498,
		y: 332,
		columns: 4,
		rows: 4,
		renderWidth: 36,
		renderHeight: 36,
		row: 1,
		idleFrame: 0,
		idleColumn: 1,
		walkFrames: [0, 1, 0, 3],
		animateAxis: "column",
		animationFrames: 4,
		animationOffset: 1,
		shadow: true,
		emote: {
			src: emoteAssets[11].src,
			x: 8,
			y: -19,
			columns: 1,
			rows: 5,
			renderWidth: 18,
			renderHeight: 18,
			animateAxis: "row",
			animationFrames: 5,
			animationOffset: 1,
		},
	},
	{
		id: "npc-3-center",
		src: npcAssets[7].src,
		x: 550,
		y: 330,
		columns: 4,
		rows: 4,
		renderWidth: 36,
		renderHeight: 36,
		row: 0,
		idleFrame: 0,
		idleColumn: 1,
		walkFrames: [0, 1, 0, 3],
		shadow: true,
		emote: {
			src: emoteAssets[9].src,
			x: 8,
			y: -18,
			columns: 1,
			rows: 5,
			renderWidth: 18,
			renderHeight: 18,
			animateAxis: "row",
			animationFrames: 5,
			animationOffset: 2,
		},
	},
	{
		id: "npc-4-right",
		src: npcAssets[8].src,
		x: 592,
		y: 334,
		columns: 4,
		rows: 4,
		renderWidth: 36,
		renderHeight: 36,
		row: 3,
		idleFrame: 0,
		idleColumn: 1,
		walkFrames: [0, 1, 0, 3],
		shadow: true,
		emote: {
			src: emoteAssets[13].src,
			x: 7,
			y: -19,
			columns: 1,
			rows: 5,
			renderWidth: 18,
			renderHeight: 18,
			animateAxis: "row",
			animationFrames: 5,
			animationOffset: 3,
		},
	},
	{
		id: "npc-5-fountain",
		src: npcAssets[9].src,
		x: 158,
		y: 508,
		columns: 4,
		rows: 4,
		renderWidth: 36,
		renderHeight: 36,
		row: 3,
		idleFrame: 0,
		idleColumn: 1,
		walkFrames: [0, 1, 0, 3],
		animateAxis: "column",
		animationFrames: 4,
		animationOffset: 2,
		shadow: true,
		emote: {
			src: emoteAssets[12].src,
			x: 7,
			y: -20,
			columns: 1,
			rows: 5,
			renderWidth: 18,
			renderHeight: 18,
			animateAxis: "row",
			animationFrames: 5,
		},
	},
	{
		id: "snpc-2-house",
		src: npcAssets[11].src,
		x: 666,
		y: 345,
		columns: 3,
		rows: 4,
		renderWidth: 36,
		renderHeight: 36,
		row: 0,
		idleFrame: 0,
		idleColumn: 1,
		walkFrames: [0, 1, 2, 1],
		animateAxis: "column",
		animationFrames: 3,
		animationOffset: 1,
		shadow: true,
		emote: {
			src: emoteAssets[3].src,
			x: 3,
			y: -20,
			columns: 1,
			rows: 5,
			renderWidth: 18,
			renderHeight: 18,
			animateAxis: "row",
			animationFrames: 5,
			animationOffset: 2,
		},
	},
	{
		id: "creature-1-construction",
		src: npcAssets[0].src,
		x: 758,
		y: 618,
		columns: 2,
		rows: 4,
		renderWidth: 30,
		renderHeight: 30,
		row: 1,
		idleFrame: 0,
		idleColumn: 0,
		walkFrames: [0, 1],
		animateAxis: "column",
		animationFrames: 2,
		shadow: true,
	},
	{
		id: "creature-2-fountain",
		src: npcAssets[1].src,
		x: 240,
		y: 687,
		columns: 2,
		rows: 4,
		renderWidth: 30,
		renderHeight: 30,
		row: 0,
		idleFrame: 0,
		idleColumn: 0,
		walkFrames: [0, 1],
		animateAxis: "column",
		animationFrames: 2,
		animationOffset: 1,
		shadow: true,
	},
	{
		id: "creature-3-garden",
		src: npcAssets[2].src,
		x: 852,
		y: 801,
		columns: 2,
		rows: 4,
		renderWidth: 30,
		renderHeight: 30,
		row: 3,
		idleFrame: 0,
		idleColumn: 0,
		walkFrames: [0, 1],
		shadow: true,
	},
	{
		id: "creature-4-route",
		src: npcAssets[3].src,
		x: 664,
		y: 765,
		columns: 2,
		rows: 4,
		renderWidth: 30,
		renderHeight: 30,
		row: 1,
		idleFrame: 0,
		idleColumn: 0,
		walkFrames: [0, 1],
		animateAxis: "column",
		animationFrames: 2,
		shadow: true,
	},
	{
		id: "creature-5-south",
		src: npcAssets[4].src,
		x: 419,
		y: 839,
		columns: 2,
		rows: 4,
		renderWidth: 30,
		renderHeight: 30,
		row: 0,
		idleFrame: 0,
		idleColumn: 0,
		walkFrames: [0, 1],
		animateAxis: "column",
		animationFrames: 2,
		animationOffset: 1,
		shadow: true,
	},
];
